services:
  sqlserver:
    networks:
      - backend
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1."
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      retries: 10
      start_period: 20s

  api-gateway:
    networks:
      - backend  
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      user-service:
        condition: service_healthy
      todo-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://api-gateway:8000/healthz"]
      interval: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  todo-service:
    networks:
      - backend
    container_name: todo-service
    build: 
      context: ./services/todo-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      sqlserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://todo-service:5000/healthz"]
      interval: 10s
      retries: 5
      start_period: 10s

  user-service:
    networks:
      - backend
    container_name: user-service
    build: 
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      sqlserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://user-service:5001/healthz"]
      interval: 10s
      retries: 5
      start_period: 10s
    
  playwright-tests:
    container_name: playwright-tests
    build: ./tests/playwright
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - ./tests/playwright/test-results:/app/test-results
    entrypoint: ["npx", "playwright", "test"]

networks:
  backend:
    driver: bridge

volumes:
  sql_data: 
