services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1."
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql  # Persistent Data Storage

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - todo-service
      - user-service

  todo-service:
    container_name: todo-service
    build: 
      context: ./services/todo-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - sqlserver

  user-service:
    container_name: user-service
    build: 
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - sqlserver

volumes:
  sql_data: 