global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['otel-collector:9464']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'gateway_(.*)'
        target_label: __name__
        replacement: '$1'

  - job_name: 'user-service'
    static_configs:
      - targets: ['otel-collector:9465']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'user_(.*)'
        target_label: __name__
        replacement: '$1'

  - job_name: 'todo-service'
    static_configs:
      - targets: ['otel-collector:9466']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'todo_(.*)'
        target_label: __name__
        replacement: '$1'
